directories:
  output: dist
  buildResources: compiled/dist
  app: compiled/dist
appId: com.ife.eduanat2
compression: maximum
productName: Eduanat2
win:
  target:
    - target: nsis
      arch:
        - ia32
nsis:
  perMachine: false
  oneClick: false
  allowToChangeInstallationDirectory : true
  runAfterFinish : false
  allowElevation : true
  packElevateHelper : true
mac:
  category: public.app-category.education
  target : 
    - target: dmg
  icon : icon.icns
  type : distribution
linux:
  category : Education
  target:
    - deb
    - rpm
deb:
  packageCategory: Education
rpm:
  packageCategory: Education
